### PR TITLE
feat(#400): add ability to map to self

### PR DESCRIPTION
**Pull request by djgilcrease**
* to do this you have the import-mapping be `file.yaml:*`

fixes: #400

### CODE REVIEW

**Comment by jamietanna** [comment]
FYI @djgilcrease your commits on GitHub aren't showing your username - mind making sure your username is associated with the email in the commit info?

**Comment by djgilcrease** [comment]
> FYI @djgilcrease your commits on GitHub aren't showing your username - mind making sure your username is associated with the email in the commit info?

Done

**Comment by S4more** [comment]
Do we have a estimate for when this is going to be merged? Seems like there is no solution for this problem.

**Comment by jamietanna** [comment]
Thanks for this! I picked this up with some additional changes in https://github.com/oapi-codegen/oapi-codegen/pull/1774

**Pull request closed without merging**
