### PR TITLE
option to include yaml tags

### PR DESCRIPTION
**Pull request by deitch**
A first attempt at resolving https://github.com/oapi-codegen/oapi-codegen/issues/1696

As request in that issue, I made it with yaml disabled by default, but could be enabled in `output-options`.

I explored making a CLI flag as well, but all of those that control config are listed as deprecated, and it says to use new config file style, so I left it as controllable via config file alone.

I probably missed something, in the tests and/or the templates. I did run it manually and it generated as expected, and I ran `make test`, so no regression should have been introduced. Looking for feedback on it.

### CODE REVIEW

**Comment by deitch** [comment]
Any feedback? I'd like to make this real. I was happy to do the work - and whatever else is needed to make it work - but I need the feedback.

**Comment by jamietanna** [comment]
We're rather snowed under with the backlog of things to review (https://github.com/oapi-codegen/oapi-codegen/discussions/1606) - please bare with!

We very much appreciate the contribution and hope to get to it before long!

**Comment by deitch** [comment]
Hi @jamietanna sure. "snowed under"? Yeah, I think I know that one all too well! Give me an ETA when you will be able to take a look? I will put it in my calendar as well to check on it.

**Comment by jamietanna** [comment]
> Give me an ETA

Sorry, I can't give any specifics, as I can't predict how long it'll take me to look at the others - given this is mostly a "free time" project, on top of ~7 hours of paid work/mo, and we're a heavily used project (which is awesome :rocket:), the work keeps on coming in, and I try and do a little bit of triage where possible of incoming issues, and then work to review the PRs when I have a bit more focused time

You can see the immediate backlog in [the v2.5.0 milestone, planned as the next release](https://github.com/oapi-codegen/oapi-codegen/milestone/11), of which I've added this into

**Comment by deitch** [comment]
Oh, yes, I certainly can relate! 😁

**Review by jamietanna — APPROVED** [review]

**Comment by deitch** [comment]
Cool! So was I in the right general direction?

**Comment by jamietanna** [comment]
You were 🎉 thanks for the contribution!

**Comment by deitch** [comment]
I am glad to be of service. 😁 

Will that go into a release anytime soon?

**Comment by jamietanna** [comment]
It'll go in when I manage to get https://github.com/oapi-codegen/oapi-codegen/milestone/11 released, I've got a full day on `oapi-codegen` today (thanks to Elastic!) but there's a lot there, so will see

In the meantime, https://github.com/oapi-codegen/oapi-codegen/?tab=readme-ov-file#pinning-to-commits

**Comment by deitch** [comment]
Yup, that is what I do on my workstation. But within a project, I prefer to mark "greater than vX.Y.Z". Not urgent, I shall await it.

**Comment by jamietanna** [comment]
As per https://github.com/oapi-codegen/oapi-codegen/milestone/11 v2.5.0

**Comment by deitch** [comment]
Thanks @jamietanna !

**Pull request merged**
