### PR TITLE
fix: extensions in properties with allOf section

### PR DESCRIPTION
**Pull request by hiddenmarten**
Hi!

Here's just a simple call that merges `allOf` section inside of the property if it's needed.

For more context, see the [issue](https://github.com/oapi-codegen/oapi-codegen/issues/1746).

### CODE REVIEW

**Comment by hiddenmarten** [comment]
Probably it would be necessary to add such functionality to other sections like `anyOf`, if you want to, please let me know.

I'll be glad to help with it.

**Comment by hiddenmarten** [comment]
Hi @jamietanna !

Should I do something in order to get a review? :)

**Comment by jamietanna** [comment]
Nope, this is in a bit of a backlog, so we'll look to review it once the 2.4.0 release is sorted. Thanks for your patience!

**Review by jamietanna — CHANGES_REQUESTED** [review]
Can we please confirm if the type changes are expected in the generated code?

```diff
  // Test defines model for test.
 type Test struct {
 	FieldA *Test_FieldA `json:"fieldA,omitempty"`
-	FieldB *TestFieldB  `json:"fieldB,omitempty"`
+	FieldB *interface{} `json:"fieldB,omitempty"`
 	FieldC *Test_FieldC `json:"fieldC,omitempty"`
 }
```

**Comment by hiddenmarten** [comment]
@jamietanna

Closed in favor to https://github.com/oapi-codegen/oapi-codegen/pull/1852

**Comment by hiddenmarten** [comment]
@jamietanna

Closed in favor to https://github.com/oapi-codegen/oapi-codegen/pull/1852

**Pull request closed without merging**
